spring.application.name=spring-ai
server.port=9292
spring.ai.openai.api-key=${OPEN_AI_KEY}
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
spring.web.resources.add-mappings=true